name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *' # Todos los días a medianoche UTC (05:00 Perú)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update dummy file
        run: |
          echo "Última actualización: $(date '+%Y-%m-%d %H:%M:%S %Z')" > last_update.txt

      - name: Commit and push
        run: |
          git add last_update.txt
          git commit -m "chore: auto commit 🤖 | $(date '+%Y-%m-%d %H:%M:%S %Z')" || echo "No changes to commit"
          git push
