name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Se ejecuta todos los días a medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente

permissions:
  contents: write  # Da permisos para modificar el repositorio

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Importante para usar GITHUB_TOKEN

      - name: Generate GitHub Stats
        run: |
          echo '###' > README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img height="150" src="https://media.giphy.com/media/1dJWnCZBCE7gcFwLvk/giphy.gif" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md
          echo '###' >> README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img src="https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=dracula&count_private=true&include_all_commits=true" height="150" alt="GitHub Stats" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=${{ github.repository_owner }}&layout=compact&langs_count=5&theme=dracula&count_private=true" height="150" alt="Top Languages" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with GitHub Stats"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.repository }}.git main
