name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecutar todos los días a medianoche
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update GitHub Stats section
        run: |
          sed -i '/<!-- STATS START -->/,/<!-- STATS END -->/c\
<!-- STATS START -->\
<div align="center">\
  <img src="https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&count_private=true&include_all_commits=true" height="150" alt="GitHub Stats" />\
  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=${{ github.repository_owner }}&layout=compact&langs_count=5&theme=radical&count_private=true" height="150" alt="Top Languages" />\
</div>\
<!-- STATS END -->' README.md

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --staged --quiet || git commit -m "chore: update GitHub stats"
          git push origin main
