name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Corregido el formato cron (faltaba un *)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que obtiene todo el historial
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Pull Latest Changes
        run: |
          git pull origin main
          
      - name: Generate GitHub Stats
        run: |
          echo '###' > README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img height="150" src="https://media.giphy.com/media/1dJWnCZBCE7gcFwLvk/giphy.gif" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md
          echo '###' >> README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img src="https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=dracula&count_private=true&include_all_commits=true" height="150" alt="GitHub Stats" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md
          echo '<div align="center">' >> README.md
          echo '  <img src="https://github-readme-stats.vercel.app/api/top-langs?username=${{ github.repository_owner }}&layout=compact&langs_count=5&theme=dracula&count_private=true" height="150" alt="Top Languages" />' >> README.md
          echo '</div>' >> README.md
          echo '' >> README.md
          
      - name: Commit and Push Changes
        run: |
          git add README.md
          git diff --staged --quiet || git commit -m "Update README with GitHub Stats"
          git push origin main
