name: Update GitHub Stats in README

on:
  schedule:
    - cron: '0 0 * * *'  # Cada día a medianoche
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que obtiene todo el historial
          
      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Pull Latest Changes
        run: |
          git pull origin main
          
      - name: Update GitHub Stats in README
        run: |
          # Crear un script temporal de Python para actualizar solo las secciones de estadísticas
          cat > update_stats.py << 'EOL'
          import re
          
          # Leer el contenido actual del README
          with open('README.md', 'r', encoding='utf-8') as file:
              content = file.read()
              
          # Definir los patrones para las estadísticas
          stats_pattern = r'<img src="https://github-readme-stats\.vercel\.app/api\?username=[^"]+"[^>]+>'
          langs_pattern = r'<img src="https://github-readme-stats\.vercel\.app/api/top-langs\?username=[^"]+"[^>]+>'
          
          # Crear las nuevas estadísticas con la fecha actual
          new_stats = f'<img src="https://github-readme-stats.vercel.app/api?username=00Andre00&show_icons=true&theme=radical&count_private=true&include_all_commits=true&border_color=00FFFF" height="150" alt="GitHub Stats" />'
          new_langs = f'<img src="https://github-readme-stats.vercel.app/api/top-langs?username=00Andre00&layout=compact&langs_count=5&theme=radical&count_private=true&border_color=00FFFF" height="150" alt="Top Languages" />'
          
          # Reemplazar las estadísticas antiguas con las nuevas
          updated_content = re.sub(stats_pattern, new_stats, content)
          updated_content = re.sub(langs_pattern, new_langs, updated_content)
          
          # Escribir el contenido actualizado de vuelta al README
          with open('README.md', 'w', encoding='utf-8') as file:
              file.write(updated_content)
          EOL
          
          # Ejecutar el script de Python
          python3 update_stats.py
          
      - name: Check for Changes
        id: check_changes
        run: |
          git diff --quiet README.md || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add README.md
          git commit -m "Update GitHub Stats in README"
          git push origin main
